### ISSUE TITLE
Update SFDMU plugin to 4.0.0

### ISSUE THREAD

**Issue by vuha-acn** [dxatscale/docker-sfpowerscripts#7]
Latest sfdmu plugin is at **sfdmu 4.0.0**

Explore upgrading the below command in Docker File to 4.0.0

# Install sfdx plugins
RUN echo 'y' | sfdx plugins:install sfdmu@3.10.5

**Comment by aly76** [comment]
SFDMU has been upgraded to 4.2.6 in the image for Release 22
